name: twinity
description: A couple leaderboard app built with Flutter and Firebase.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.1
  google_sign_in: ^6.3.0
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

dependency_overrides:
  js: ^0.7.2
