name: twinity
description: A couple leaderboard app built with Flutter and Firebase.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Updated Firebase Packages
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  cloud_functions: ^4.6.8
  firebase_storage: ^11.6.9

  # Other Packages
  google_sign_in: ^6.2.1
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.1.13
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true