// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkVT0hoekrgRcjUKk2quv_J6WQRctmeaM',
    appId: '1:699003558638:web:6c9136367c6fd03dacb1ff',
    messagingSenderId: '699003558638',
    projectId: 'twinity-app',
    authDomain: 'twinity-app.firebaseapp.com',
    storageBucket: 'twinity-app.firebasestorage.app',
    measurementId: 'G-CX47Q4JJFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGLtz0fHn647iAJQ0M0wTW472H8kr5rRI',
    appId: '1:699003558638:android:84053ddf8b343170acb1ff',
    messagingSenderId: '699003558638',
    projectId: 'twinity-app',
    storageBucket: 'twinity-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWz1gEyjksMKWQPsz-4uLi9TYrhtWabFU',
    appId: '1:699003558638:ios:a2d2a1153090fce6acb1ff',
    messagingSenderId: '699003558638',
    projectId: 'twinity-app',
    storageBucket: 'twinity-app.firebasestorage.app',
    iosBundleId: 'com.example.twinity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWz1gEyjksMKWQPsz-4uLi9TYrhtWabFU',
    appId: '1:699003558638:ios:a2d2a1153090fce6acb1ff',
    messagingSenderId: '699003558638',
    projectId: 'twinity-app',
    storageBucket: 'twinity-app.firebasestorage.app',
    iosBundleId: 'com.example.twinity',
  );
}
